---
latitude: 40.70947
longitude: -74.01394
map_zoom: 12
name: World Center Hotel
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 144 Washington St
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10006'
_hotel_id: WOR856
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
